### PR TITLE
Dataset editing

### LINKED ISSUE #42: Allow editing of data set
The curator should be able to control the editing. For example after r1 calculation has failed.

### PR DESCRIPTION
**Pull request by alesgenova**
Fixes #42

### CODE REVIEW

File: client/src/components/dataset/editToggle.js [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+}
+
+function mapStateToProps(state, ownProps) {
+  let props = {
+    dataset: null
+  };
+
+  if (!_.isNull(ownProps._id)) {
+    let dataset = selectors.datasets.getDatasetById(state, ownProps._id);
+    props['dataset'] = dataset;
```
Comment (cjh1) [inline client/src/components/dataset/editToggle.js]: `props.dataset = dataset`?

File: client/src/components/dataset/index.js [hunk 2]
```diff
@@ -133,31 +140,40 @@ class Dataset extends Component {
     const species = this.props.atomicSpecies.map((an) => symbols[an]).join(', ');
     const authors = this.props.authors.join(' and ');
 
+    let isPublic = !_.isNil(this.props.public) && this.props.public ? true : false;
```
Comment (cjh1) [inline client/src/components/dataset/index.js]: I think this can just be:
`_.isNil(this.props.public) && this.props.public`

File: server/materialsdatabank/server/models/dataset.py [hunk 3]
```diff
@@ -61,13 +62,23 @@ def create(self, authors, title=None, url=None, microscope=None, image_file_id=N
 
         return self.save(dataset)
 
-    def update(self, dataset, user=None, atomic_species=None, validation=None,
+    def update(self, dataset, dataset_updates=None, user=None, atomic_species=None, validation=None,
```
Comment (cjh1) [inline server/materialsdatabank/server/models/dataset.py]: Should we move atomic_species into dataset_updates?

File: server/materialsdatabank/server/rest.py [hunk 4]
```diff
@@ -93,10 +93,40 @@ def create_dataset(self, dataset):
         .jsonParam('updates', 'Update document', required=True, paramType='body')
     )
     def update_dataset(self, id, updates):
+        # Datasets are only editable if the current user is a curator,
+        # or if the editable field on the dataset is true
+
+        isCurator = False
+
+        curatorGroup = list(Group().find({
```
Comment (cjh1) [inline server/materialsdatabank/server/rest.py]: snake

File: server/materialsdatabank/server/rest.py [hunk 5]
```diff
@@ -93,10 +93,40 @@ def create_dataset(self, dataset):
...
+        }))
+
+        if len(curatorGroup) > 0:
+            user = self.getCurrentUser()
+            groups = user['groups']
+
+            if curatorGroup[0]['_id'] in groups:
+                isCurator = True
+        else:
+            raise RestException('Unable to load group. Please check correct groups have been configured.')
```
Comment (cjh1) [inline server/materialsdatabank/server/rest.py]: snakes

File: server/materialsdatabank/server/rest.py [hunk 6]
```diff
@@ -93,10 +93,40 @@ def create_dataset(self, dataset):
...
+        curatorGroup = list(Group().find({
+            'name': 'curator',
+        }))
+
+        if len(curatorGroup) > 0:
+            user = self.getCurrentUser()
+            groups = user['groups']
+
+            if curatorGroup[0]['_id'] in groups:
+                isCurator = True
```
Comment (cjh1) [inline server/materialsdatabank/server/rest.py]: Doesn't we have this code somewhere else? We might want `is_curator` utility function?
